### ISSUE TITLE
New layers are added at the bottom of the layer tree instead of above the selected layer

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/solocator#1]
When adding a new WMS layer througth SO-Locator, the new layer appears at the bottom of the layer tree.

We would expect the same behavior like QGIS standard:
- if a layer is selected, it is added above the selected layer.
- if no layer is selected, the new layer is added to the top of the layer tree, unless it is of type background layer
- background layers are always added to the bottom

**Comment by 3nids** [comment]
this is partially fixed in 0.2.1

**Comment by 3nids** [comment]
this is done, I am only leaving this open as a reminder for upcoming background layers

**Comment by 3nids** [comment]
closing in favor of #16
