### ISSUE TITLE
Loading of facade layer as separate layers throws error message

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/solocator#17]
When trying to load a facade layer as separate WMS layers, there is an error message:
Layer xxx could not be correctly loaded. Please contact the support.

Examples:
Search for "PLZ und Ortschaften" or "Relief digitales Oberflächenmodell (LiDAR 2018)".

Unchecking the checkbox "Als separate Layer laden" leads to a correct loading of the WMS layer as a combined WMS layer.

I think that Facade layers, when loaded as WMS, should just ignore the setting of the checkbox "Als separate Layer laden" and always load as a single, combined WMS layer.

**Comment by 3nids** [comment]
there seem to be an issue in the response from the service:
layer from the service: `ch.so.agi.gebaeudeadressen.ortschaften`

layer in GetCapabilities: 
![image](https://user-images.githubusercontent.com/127259/66655359-33a2a200-ec3c-11e9-9f3b-8e1e04e398e6.png)

**Comment by andreasneumann** [comment]
Could be - but all of the "Facade Layers" have this very same problem. I think the facade layers are not meant to be loaded individually. If the top layer "ch.so.agi.gebaeudeadressen.plz_ortschaften" is loaded, it should be ok.

**Comment by 3nids** [comment]
fixed in https://github.com/opengisch/solocator/releases/tag/1.0.1
