### ISSUE TITLE
Store authcfg instead of username and password in layer datasource

### ISSUE THREAD

**Issue by schmandr** [opengisch/solocator#19]
When in SoLocator credentials of the QGIS authentication database are configured for PostgreSQL layers (Basic Authentication credentials from the authentication DB as an example), SoLocator should store the _authcfg_ id instead of the username and password when adding the layer. So we can avoid usernames and passwords to appear in .qgs documents.

**Comment by 3nids** [comment]
I am not sure how to handle this at the moment, I have asked here https://gis.stackexchange.com/questions/338671/pyqgis-adding-a-layer-with-an-auth-config-id-leaks-into-the-project before digging on my own.
