### ISSUE TITLE
Benutzerführung

### ISSUE THREAD

**Issue by edigonzales** [opengisch/solocator#20]
To be discussed @schmandr @andreasneumann @uncoyote

Ich finde es noch zu verwirrend, wenn man es mit Layergruppen/Facadelayern zu tun bekommt.

Wenn ich "Fixpunkte" eintippe, sehe ich nur "Amtliche Vermessung". Es gibt ein Plus, dass ich nicht aufklappen kann. Wenn ich es "aufklappen" will, muss ich Ctrl+Doppelclick machen. Dann gibt es verschiedene Einstellungen und einen je nach Komplexität der Layergruppen grösseren Layerbaum und ich muss die Fixpunkte ggf suchen.

- Sinnvoll fixbar?
- Bringt man die WMS-Welt mit der DB-Tabellenwelt überhaupt gut zusammen?

**Comment by andreasneumann** [comment]
See also #26 - sollte schon etwas Verbesserung bringen. Noch auszuprobieren mit dem nächsten Release.

**Comment by andreasneumann** [comment]
This issue should be closed.
