### ISSUE TITLE
Use the "service" connection parameter for PostgreSQL layers

### ISSUE THREAD

**Issue by schmandr** [opengisch/solocator#21]
Via the code or via the configuration options, the plugin configures the _dbhost_, _dbname_ and _port_ connection parameters for PostgreSQL layers. Additionally, it should be possible to specify a PostgreSQL service name (_service=_) instead of these three parameters. Or even better, to specify a service name and zero or more of these three params (allows overriding the params defined in the service file if needed).

This is because for manual adding of PostgreSQL layers, we rely on a PostgreSQL service name. If one day we happen to e.g. rename our database or the DB host, we need to change this in the PostgreSQL connection service file only, and there is no need to change it in every .qgs document that contains PostgreSQL layers added by the SoLocator plugin.

The default for the service name must be _pub_, and by default, no dbhost, dbname and port should be configured. (i.e. _service=pub_ only.)

**Comment by 3nids** [comment]
fixed in 1.1.0
