### ISSUE TITLE
Add option of image format when loading WMS layergroup/datasetview

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/solocator#3]
Ctrl-Click on a datasetview or layergroup should open a separate config dialogue, showing metadata and giving user some options on how to load a layer.

It should be possible for the user to choose an image format from the formats the WMS server supports (e.g. png, png8, jpeg, webp).

**Comment by 3nids** [comment]
is the set of image formats exactly these 4 ones?

**Comment by andreasneumann** [comment]
Can we detect the information about available image formats from a GetCapabilities request? This would be more flexible. I would assume that png and jpeg are almost always available, but webp or png8 might or might not be available.

**Comment by 3nids** [comment]
mabye, but I would suggest to try to strictly use the service to avoid to make an extra request.
Also, this would be a per layer configuration.
What do you think?

**Comment by andreasneumann** [comment]
You mean that our dataproduct service (https://geo.so.ch/api/dataproduct/v1/) should provide the information which data formats are available for the WMS service?

Well given the fact that the custom image format would only be available if the user ctrl-double clicks a result, the extra request wouldn't be that bad. If the user double clicks without the ctrl, always png should be used except for background layers, where jpeg would be preferred.

In case of a group layer and the user selects more than one layer, I think all should have the same image format.

**Comment by 3nids** [comment]
I could not find any layer supporting PNG8 or WEBP in https://geo.so.ch/api/wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0

**Comment by andreasneumann** [comment]
I am talking about "image/png; mode=8bit"

webp is not yet available because we still run QGIS 2.18. It will be available, once we switch to QGIS3.

**Comment by 3nids** [comment]
> You mean that our dataproduct service (https://geo.so.ch/api/dataproduct/v1/) should provide the information which data formats are available for the WMS service?

yes, that would be easier but it all depends, is this a per-layer capability or per server?

> Well given the fact that the custom image format would only be available if the user ctrl-double clicks a result, the extra request wouldn't be that bad. If the user double clicks without the ctrl, always png should be used except for background layers, where jpeg would be preferred.

I am not sure we should ever use jpeg. Let's say you want a colored background on your map?

In the end, shall I just provide a combobox with a format that is used for all?

**Comment by andreasneumann** [comment]
I just tested the new version 0.6.0

The GUI looks good, however, no matter if I choose jpeg or png it seems that always png is loaded.

**Comment by andreasneumann** [comment]
![image](https://user-images.githubusercontent.com/884476/66546351-205cdd00-eb3d-11e9-9fd4-91cb6fe57d7a.png)

There is a typo in the german translation. The "s" at the end of Layers should be removed.
