### ISSUE TITLE
Allow selecting an "authcfg" even if using a PostgreSQL service name

### ISSUE THREAD

**Issue by schmandr** [opengisch/solocator#30]
In the case when the user wants to load the layer as PostgreSQL layer, it should always be possible to select an "authcfg", even if the user chooses to use a PostgreSQL service name for connecting to the DB. So an "authcfg" must be selectable no matter if the user chooses to connect with a PostgreSQL service name or with PostgreSQL Host name, DB Name and Port.

**Comment by 3nids** [comment]
Isn't possible with the current configuration? You can choose between service name and authcfg.

**Comment by andreasneumann** [comment]
@3nids - we would like to be able to combine the service with the credentials of a selected authcfg

**Comment by 3nids** [comment]
ok, so both service and authcfg would be opt in?

**Comment by andreasneumann** [comment]
Both are normally required, otherwise I guess the PG layers probably can't be loaded. But, yes there could be cases where the authentication is already in the service configuration.

**Comment by 3nids** [comment]
fixed in d1db29b463916a2208f25ae4d9a5bf8483cacb6b
