### ISSUE TITLE
PostGIS should be the default when loading a layer with double click

### ISSUE THREAD

**Issue by schmandr** [opengisch/solocator#32]
In case this i not possible: Switch automatically to WMS (e.g. orthofoto layers)

**Comment by 3nids** [comment]
this is a "remembered" option: last mode is selected by default.
If the plugin is used outside of the intranet, I guess it makes sense to keep the current behavior.
Or is there an intelligent way to detect if we have access?

**Comment by andreasneumann** [comment]
It is good, that this setting can be changed and remembered. It's a good point, if the plugin is used outside of the Intranet, to allow the user to make WMS the default.

Perhaps it would make sense to expose this setting globally in the SoLocator settings dialogue, e.g. before the group box for WMS settings.

**Comment by 3nids** [comment]
not relevant anymore

**Comment by andreasneumann** [comment]
This needs to be re-opened. For new installations, PostgreSQL should be the default connection mode. In the current version 1.2.0 this is not yet the case:

![image](https://user-images.githubusercontent.com/884476/68591387-ef9bfa80-0490-11ea-97e9-e296a8eb9122.png)
