### ISSUE TITLE
List of layers that should be loaded with the jpeg image format when loading as WMS layer

### ISSUE THREAD

**Issue by schmandr** [opengisch/solocator#34]
Provide hidden configuration option that contains a list of layer IDs that should be loaded with the jpeg image format.

Remove png/jpeg option from UI.

**Comment by andreasneumann** [comment]
The long term goal is that the data product service will provide a hint if the layer should be loaded as png or jpeg image format. But this will take a while, and until this is available, we would like to maintain a delimited list of data product names that should be loaded as jpeg instead of png

**Comment by andreasneumann** [comment]
Layers that should be loaded as JPEG instead of PNG:
Every Layer that has "Hintergrundkarte" in it's name and every layer that has "Orthofoto" in it's name.
