### ISSUE TITLE
Children of layergroups should always be displayed, not filtered away based on search-string

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/solocator#46]
The children of layer groups should all be displayed, regardless of the match of the search string against the "display" attribute of the layer in the search result:

Test case:

https://geo-i.so.ch/api/search/v2/?searchtext=Richtplan&filter=foreground,background,ch.so.agi.gemeindegrenzen,ch.so.agi.av.gebaeudeadressen.gebaeudeeingaenge,ch.so.agi.av.bodenbedeckung,ch.so.agi.av.grundstuecke.projektierte,ch.so.agi.av.grundstuecke.rechtskraeftig,ch.so.agi.av.nomenklatur.flurnamen,ch.so.agi.av.nomenklatur.gelaendenamen,ch.so.agi.agi_hoheitsgrenzen_pub.hoheitsgrenzen_gemeindegrenze&limit=20

Search for "Richtplan" should display also the children of Naturgefahrenhinweiskarte:

```
Richtplan
-	Richtplan Vorhaben (Richtplan)
-	Richtplan Ausgangslage (Richtplan)
Abbaustellen
Naturgefahrenhinweiskarte
-	Karst
-	Steinschläge
-	Rutschungen
-	Wassergefahren
```

**Comment by 3nids** [comment]
apparently the server is down?

**Comment by 3nids** [comment]
it's back online :)
