### ISSUE TITLE
Please provide an English description

### ISSUE THREAD

**Issue by pcav** [opengisch/solocator#48]
so more people will be able to understand plugin usefulness

**Comment by andreasneumann** [comment]
Hi @pcav - where do you want the english description? At https://github.com/opengisch/solocator or in the plugin metadata?
Greetings,
Andreas

**Comment by pcav** [comment]
In the metadata please, so it wiill appear in the description in the plugin manager and in the plugin website, and interested users and developers can understand whether the plugin can be of use.
Thanks.

**Comment by andreasneumann** [comment]
See https://github.com/opengisch/solocator/pull/50
