### ISSUE TITLE
Switch search and dataproduct services to the production environment

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/solocator#51]
We need to switch the URLs of the search and dataproduct services to our production environment.

So far it isn't possible yet, because the change for foreground/background data is not yet rolled out in the production environment.

This needs to be coordinated with the Sogis-Team to get the timing right.

**Comment by 3nids** [comment]
We can easily plan this ahead. Just le me know the details. We can even have it ready here (on Github) as pre-release.

**Comment by andreasneumann** [comment]
We have a new service rollout on Monday evening, Nov 25. But we'll first have to make sure that the service works as expected. So ideally, we could do that switch on Nov 26 some time on the afternoon. or Nov 27.

**Comment by andreasneumann** [comment]
This has now - finally - been rolled out. The Service-URL to be used now is https://geo.so.ch/api

Thanks,
Andreas

**Comment by 3nids** [comment]
I just released 1.3.0 which should be available within 30 minutes or so on the plugin repo.
Let me know if everything is fine.
