### ISSUE TITLE
UI indicator for longer loading of larger layer groups

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/solocator#52]
When loading layer groups (both PG and WMS), the loading can take quite some time: several seconds, sometimes more than a minute.

Would it be possible to:
- either load in a separate background thread (if this is technically possible)
- or have an indicator telling the user that SoLocator is still active and he has to be patient until the layers are loaded. (would this be technically possible?)

**Comment by 3nids** [comment]
I added  a waiting cursor, let's see if it's enough

**Comment by andreasneumann** [comment]
Good - let's see how that works. I understand that solutions like background threads are quite complicated and would trigger other problems.

Hopefully that waiting cursor helps to show users that QGIS is busy loading larger layer groups.

**Comment by andreasneumann** [comment]
Looks good to me. I am closing this issue.
