### ISSUE TITLE
Set default PG Service "pub" by default

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/solocator#55]
We should set the default pg service name to "pub" by default. We prefer PG connection strings with the service name instead of the host/port/db etc. combo.

![image](https://user-images.githubusercontent.com/884476/69344706-1ec02200-0c70-11ea-95d7-1beaf51f7fbc.png)

**Comment by andreasneumann** [comment]
This should be done in a way similar to the default "Service URL" and "PG Host": if the user presses the "delete" button in the text edit widget, it should fill in "pub" as default. Otherwise, for testing purposes the user could replace that string.

**Comment by 3nids** [comment]
Ok, this means that it will defined in the computer. Otherwise, the plugin will fail to load the layer.

**Comment by andreasneumann** [comment]
yes - we always roll out a service configuration with QGIS.
