### ISSUE TITLE
Moving hints to foreground maps breaks layer loading

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/solocator#57]
The commit https://github.com/opengisch/solocator/commit/3c6845f22ee3a6ea55df36a894fff3699853dd0d

had an unwanted side effect. The change of the string seems to prevent the display of layers in the search result.

Currently, we can't load layers.

See also my comments at https://github.com/opengisch/solocator/commit/3c6845f22ee3a6ea55df36a894fff3699853dd0d#commitcomment-36085424

**Comment by 3nids** [comment]
fixed in 5080743

**Comment by andreasneumann** [comment]
Excellent - thanks!
