### ISSUE TITLE
QGIS 3.4 and SoLocator combo hangs on closing of QGIS

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/solocator#60]
There is a suspicion that the combination of QGIS 3.4 with SoLocator plugin makes QGIS hang on closing QGIS. QGIS 3.10 doesn't seem to be affected. But with QGIS 3.4 I can see this problem on both Linux and Windows.

To reproduce:
1.	install SoLocator plugin in QGIS 3.4
2.	Open the "Settings"  "Options"  "Locator"  "SoLocator" Settings (the cogwheel icon)
3.	Close the settings again
4.	Close QGIS  QGIS hangs on closing

**Comment by andreasneumann** [comment]
Update: I just compiled the very latest 3.4 version from github and the issue is still present.

**Comment by 3nids** [comment]
I confirm the freeze on 3.4 on Mac.

**Comment by andreasneumann** [comment]
Do you think it is an issue in QGIS core or something that can be fixed in the plugin?

**Comment by 3nids** [comment]
I currently have no idea. We have a crash in a similar scenario with another locator filter plugin. I supsect there is something wrong in core. This requires more investigation, I should be able to dig in next week,

**Comment by andreasneumann** [comment]
> This requires more investigation, I should be able to dig in next week,

Thanks!
