### ISSUE TITLE
Python error in QGIS >= 3.10 when trying to load a layer

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/solocator#63]
Whenever I try to load a PG layer or layergroup (double click in search result, e.g. "Nutzungsplanung") in QGIS 3.10 or master I receive the following Python error:

```
SystemError: returned a result with an error set 
SystemError: ../Objects/dictobject.c:1561: bad argument to internal function

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bjsvwneu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/solocator/core/solocator_filter.py", line 327, in triggerResult
    if type(result.userData) == NoResult:
SystemError:  returned a result with an error set


Python-Version: 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0] 
QGIS-Version: 3.13.0-Master Master, 59ce5c8d65 

Python-Pfad:
/usr/local/share/qgis/python
/home/bjsvwneu/.local/share/QGIS/QGIS3/profiles/default/python
/home/bjsvwneu/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/local/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/bjsvwneu/.local/share/QGIS/QGIS3/profiles/default/python
```

**Comment by 3nids** [comment]
A quick first search on the error leads to some binary compatibility issues on Python 3.7/Linux.
(https://github.com/gevent/gevent/issues/1261 points to https://github.com/gevent/gevent/issues/1260)

I am not 100% sure. But it would be nice to test on another system before I invest more time here.

On my computer, I don't have any issue to load a layer group under QGIS 3.13.

**Comment by andreasneumann** [comment]
Ok - let's put in hold for now until I can do further testing. Still fighting with my sysadmins to get access to all necessary resources on my Virtualbox test sytem. I will ping you again.

**Comment by andreasneumann** [comment]
On Windows 3.10 this is a non-issue. Might be something local on my Linux machine.

Closing this ticket.
