### ISSUE TITLE
SoLocator fails to work in QGIS 3.16

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/solocator#64]
Seems like SoLocator doesn't properly work with QGIS 3.16

One can search properly, but when double-clicking a result-one gets a Python error message:

```
2021-05-05T08:44:14     WARNING    Traceback (most recent call last):
              File "/home/bjsvwneu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/solocator/core/network_access_manager.py", line 329, in replyFinished
              self.request(redirection_url.toString())
              File "/home/bjsvwneu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/solocator/core/network_access_manager.py", line 243, in request
              raise self.http_call_result.exception
             solocator.core.network_access_manager.RequestsExceptionUserAbort: Network error: Operation abgebrochen
             
2021-05-05T08:44:31     WARNING    SystemError: ../Objects/dictobject.c:1561: bad argument to internal function
             
             The above exception was the direct cause of the following exception:
             
             Traceback (most recent call last):
              File "/home/bjsvwneu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/solocator/core/solocator_filter.py", line 327, in triggerResult
              if type(result.userData) == NoResult:
             SystemError: returned a result with an error set
```

Can you please have a look why this fails on QGIS 3.16?

Tested with QGIS 3.16.6 on Windows (there it even crashes QGIS) and on QGIS 3.16.4 on Linux where it doesn't crash QGIS but still fails to work.

Thanks!

**Comment by andreasneumann** [comment]
I believe that the first error message is unrelated to the problem (different issue). It also appears on QGIS 3.10, but usually only after QGIS startup (I believe).

**Comment by 3nids** [comment]
This should have been fixed by @m-kuhn in https://github.com/qgis/QGIS/pull/40471 a few months ago. It has been integrated in 3.16.2.

similar issue has been reported in https://github.com/opengisch/qgis-swiss-locator/issues/9

Can you confirm which exact release version you use?

**Comment by 3nids** [comment]
it's maybe a different issue. Let me check a bit more.

**Comment by andreasneumann** [comment]
We have installed https://github.com/qgis/QGIS/commit/bfd36fdd

```

QGIS-Version
3.16.6-Hannover
QGIS-Codeversion
bfd36fdd
Kompiliert gegen Qt
5.15.2
Laufendes Qt
5.15.2
Kompiliert mit GDAL/OGR
3.2.2
Läuft mit GDAL/OGR
3.2.2
Kompiliert mit GEOS
3.9.1-CAPI-1.14.2
Läuft mit GEOS
3.9.1-CAPI-1.14.2
Kompiliert mit SQLite
3.35.2
Läuft mit SQLite
3.35.2
PostgreSQL-Client-Version
13.0
SpatiaLite-Version
5.0.1
QWT-Version
6.1.3
QScintilla2-Version
2.11.5
Kompiliert mit PROJ
8.0.0
Läuft mit PROJ
Rel. 8.0.0, March 1st, 2021
BS-Version
Windows Server 2012 R2 Version 6.3 (Build 9600)
Aktive Python-Erweiterungen
plugin_reloader; 
QgisModelBaker; 
QuickWKT; 
solocator; 
trackable_project_files; 
db_manager; 
processing

```

**Comment by andreasneumann** [comment]
On Windows it runs with Python3.9 on my Linux test systems with Python3.6 (Ubuntu 18.04) or Python 3.8 (Ubuntut 20.04). All seem to fail.

**Comment by 3nids** [comment]
@andreasneumann can you try experimental version: https://github.com/opengisch/solocator/releases/tag/1.3.99
direct link to zip: https://github.com/opengisch/solocator/releases/download/1.3.99/solocator.1.3.99.zip

**Comment by andreasneumann** [comment]
Thanks.

I tested (on Windows for now) and I get a different error now:

```
2021-05-05T09:34:09     WARNING    Traceback (most recent call last):
              File "C:/Users/bjsvwneu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\solocator\core\solocator_filter.py", line 327, in triggerResult
              if type(self.get_user_data(result)) == NoResult:
             AttributeError: 'SoLocatorFilter' object has no attribute 'get_user_data'
```

**Comment by m-kuhn** [comment]
https://qgis.org/api/classQgsLocatorResult.html#a178710ec2ccca064ed20a83439d213a1 ?

**Comment by 3nids** [comment]
https://github.com/opengisch/solocator/releases/tag/1.3.991 should be good

https://github.com/opengisch/solocator/releases/download/1.3.991/solocator.1.3.991.zip

**Comment by andreasneumann** [comment]
Yes, this version seems to work. Thank you for the fast fix.

I see a lot of messages in the "Locator Bar" protocol tab. Is this due to the fact that this is a "debug" version? Will this be supressed in the release version?
