### ISSUE TITLE
Can't load single WMS layer directly due to uninitalized variable "wms_load_separate"

### ISSUE THREAD

**Issue by andreasneumann** [opengisch/solocator#8]
If one tries to load a single WMS layer directly (without the ctrl-double click and the separate config dialogue) there is an error message about a variable referenced before assignment:

Example: "Wald - Übersicht"

`
UnboundLocalError: local variable 'wms_load_separate' referenced before assignment 
Traceback (most recent call last):
  File "/home/bjsvwneu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/solocator/core/solocator_filter.py", line 413, in 
    self.nam_fetch_feature.finished.connect(lambda response: self.parse_data_product_response(response, open_dialog))
  File "/home/bjsvwneu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/solocator/core/solocator_filter.py", line 424, in parse_data_product_response
    LayerLoader(data, open_dialog, self.iface)
  File "/home/bjsvwneu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/solocator/core/layer_loader.py", line 74, in __init__
    data.load(insertion_point, load_as_pg, wms_load_separate, pg_auth_id)
UnboundLocalError: local variable 'wms_load_separate' referenced before assignment
`

**Comment by andreasneumann** [comment]
We need to distinguish here based on the data-product type:
Group layers should be loaded as several individual layers, facade layers as single layer.

If a facade layer is in a group layer then it would be a mixture.

**Comment by 3nids** [comment]
OK, but then how does the option would change the behavior?

**Comment by andreasneumann** [comment]
As a consequence of the above mentioned default behaviour I think that the WMS option "load as separate" layer should be made the default.

If the user unchecks this checkbox, then only one single QGIS layer, containing the whole group or more than one selected sub layers combined into a single layer should be loaded.

**Comment by 3nids** [comment]
just to be sure, are you saying that facade layer should be loaded as WMS all the time (without loading as separate layers)?

**Comment by 3nids** [comment]
ok, so facade layers should never be loaded as separate even if the option is checked, correct?

**Comment by andreasneumann** [comment]
yes - in case of WMS. In case of Postgis, of course they need to be loaded as separate layers, but the individual layers should be put into the group with the name of the facade layer.

**Comment by 3nids** [comment]
ok.
But this brings us to new complexity with the multiple selection: you might be able to uncheck part of a facade layer sublayers. What do we do then? Still load it as a single layers no matter what is checked under it?

**Comment by andreasneumann** [comment]
Not sure. The facade layers are mainly a concept that makes sense in the context of WMS. For Postgis, the facade layers have no special meaning, other than maybe it would make sense to have them in an extra group.

So my suggestion is to ignore selections in the sub layers if the user wants a WMS, but take them into account when the user wants Postgis.

What do you think?

**Comment by 3nids** [comment]
I'd say it depends on the need of fine tuning. In any case, it would still be possible I guess by choosing a single layer in the layer tree.
Let's try like that and wait for user experience

**Comment by andreasneumann** [comment]
ok - sounds good.
